version: '3.4'

services:
  nginx_api:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/public:/srv/app/public:ro
    ports:
      - "86:80"
      - "443:443"
    networks:
      - proxy
    depends_on:
      - node_api
    links:
      - node_api

  node_api:
    env_file:
      - .env
    build:
      context: ./docker/node
    command: npm run start:debug
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_DEBUG_PORT}:${APP_DEBUG_PORT}"
    networks:
      - proxy
      - api_internal
    volumes:
      - ./app:/srv/app:rw
    depends_on:
      - mariadb_api
    links:
      - mariadb_api

  mariadb_api:
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_volume_api:/var/lib/mysql
      - ./docker/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - api_internal
      - db_proxy

volumes:
  mariadb_volume_api:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './mariadb'

networks:
  api_internal:
    internal: true
  proxy:
    external: true
  db_proxy:
    external: true